#!/usr/bin/env bash
# Copyright 2019-2021 releng-tool
set -e

while [ "$#" -gt 0 ]; do
    case $1 in
        -L|--locale)
        locale_dir="$2"
        shift
        ;;
    esac
    shift
done

# find absolute path to locale directory (if provided and exists)
if [ -n "$locale_dir" ]; then
    locale_dir="$(cd "$(dirname "$locale_dir")"; pwd -P)/$(basename "$locale_dir")"
fi

set -e

base="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
source $base/common
source $base/settings
out_dir=$base/_build

# cleanup legacy working directory
rm -rf $base/$workdir
rm -rf $out_dir

if [ -z "$locale_dir" ]; then
    locale_dir=$base/$workdir/$locale_container

    mkdir -p $locale_dir
    git \
        --git-dir="$base/$cache/$locale_container" \
        --work-tree="$locale_dir" \
        checkout master --force
fi

source $locale_dir/settings

# ensure translations are up-to-date
$base/support --generate-translation-objects

# include a "latest" version pointing to most_stable_version
versions+=(['latest']=${versions[$most_stable_version]})
ordered_versions="latest,$ordered_versions"

for version in "${!versions[@]}"; do
    reference=${versions[$version]}

    # compile a list of supported languages for this version
    support_version=$version
    if [[ "$support_version" == 'latest' ]]; then
        support_version=$most_stable_version
    fi

    languages=('en')
    for ref in $(ls -d $locale_dir/locale-$support_version/*/); do
        lang_dir=${ref%%/}
        lang=${lang_dir##*/}

        # skip pot directory
        if [[ "$lang" == 'pot' ]]; then
            continue
        fi

        languages+=($lang)
    done

    # compile a list of languages
    lang_list=$(printf ",%s" "${languages[@]}")
    lang_list=${lang_list:1}

    for lang in "${languages[@]}"; do
        target_dir=$out_dir/$lang/$version
        echo -e "\e[7mbuilding $version ($lang)...\e[0m"

        # checkout specific documentation version
        mkdir -p $base/$workdir/$doc_container
        git \
            --git-dir="$base/$cache/$doc_container" \
            --work-tree="$base/$workdir/$doc_container" \
            checkout $reference --force

        # build documentation
        export RELENG_LANGUAGE=$lang
        export RELENG_LANGUAGES=$lang_list
        export RELENG_LOCALE_DIR=$locale_dir/locale-$support_version/
        export RELENG_STABLE=$most_stable_version
        export RELENG_VERSION=$version
        export RELENG_VERSIONS=$ordered_versions
        python -m sphinx \
            -Dlanguage=$lang \
            -b $builder \
            $base \
            $target_dir
    done
done
