#!/usr/bin/env bash
# Copyright 2019-2021 releng-tool
set -e

# cache base directory for git sources
cache=.releng_cache

# working base directory for git sources
workdir=.releng_work

# folder with documentation information
doc_container=releng-tool

# folder with locale information
locale_container=translations

# sphinx builder to invoke
builder=dirhtml
