#!/usr/bin/env bash
# Copyright 2019 releng-tool
set -e

# folder with documentation information
doc_container=releng-tool

# folder with locale information
locale_container=translations

# sphinx builder to invoke
builder=html
