#!/usr/bin/env bash
# Copyright 2019 releng-tool
set -e

################################################################################

# documentation repository
doc_repo=https://github.com/releng-tool/releng-tool.git

# repository with locale information
locale_repo=https://github.com/releng-tool/releng-tool-doc-translations.git

################################################################################

base="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
source $base/common

# build repositories
if [ ! -d "$base/$cache/$doc_container" ]; then
    echo 'building repositories...'
    git init --bare $base/$cache/$doc_container
    git --git-dir="$base/$cache/$doc_container" \
        remote add origin $doc_repo
fi
if [ ! -d "$base/$cache/$locale_container" ]; then
    echo 'building repositories...'
    git init --bare $base/$cache/$locale_container
    git --git-dir="$base/$cache/$locale_container" \
        remote add origin $locale_repo
fi

# fetch all from repositories
echo 'ensuring most recent data from repositories...'
git --git-dir="$base/$cache/$doc_container" fetch --all
git --git-dir="$base/$cache/$locale_container" fetch --all

# disable detached head message
git --git-dir="$base/$cache/$doc_container" config advice.detachedHead false
git --git-dir="$base/$cache/$locale_container" config advice.detachedHead false

echo 'ready!'
